Hectione/Hectione/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('blog.urls',namespace='blog')),
]

urlpatterns+= staticfiles_urlpatterns()

Hectione/blog/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = "blog"

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^about/',views.AboutView.as_view(),name='about'),
    url(r'^contact/',views.contactFormView,name='contact'),
    url(r'^blog/',views.PostListView.as_view(),name='post_list'),
    url(r'^thanks/',views.ThanksView.as_view(),name='thanks'),
    #url(r'^blog/')
]

Hectione/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):

    title = models.CharField(max_length=150)
    slug = models.SlugField()
    content = models.TextField()
    updated_on = models.DateField()
    created_on = models.DateField()
    author = models.CharField(max_length=100)
    #status =

    def __str__(self):
        return(self.title)

Hectione/blog/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea(attrs={"rows":2, "cols":20}))

Hectione/blog/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,ListView,DetailView
from blog.models import Post
from django.utils import timezone
from . import forms
# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'


class ThanksView(TemplateView):
    template_name = 'thanks.html'


class PostListView(ListView):
    model = Post
    # context_object_name = 'post_list'

    def get_queryset(self):
        # return Post.objects.filter(created_on__lte=timezone.now()).order_by('-created_on')
        return Post.objects.filter()


# class PostDetailView(DetailView):
#     model = Post

def contactFormView(request):
    form = forms.ContactForm


    if(request.method == 'POST'):
        form = forms.ContactForm(request.POST)

        if form.is_valid():
            print("name "+form.cleaned_data['name'])
            print("email "+form.cleaned_data['email'])
            print("message "+form.cleaned_data['message'])

            return redirect('/thanks/')
    else:
        form = forms.ContactForm

    return render(request,'contact.html',{'form':form})

Hectione/blog/templates/blog/about.html
{% extends "base.html" %}
{% block prenavbar %}
{% endblock%}
{% block navbar %}
<div class="home">
<div class="container">
  <div class="box">
    <h3>
    Hi, I'm Anagha.
    <br>
    I'm a very creative person and a passionate developer.
    <br>
    So, I decided to create my personal blog myself and here it is. <br>
    Please take a tour through my articles and post your valuable feedbacks.
  </h3>
  </div>
</div>
</div>
{% endblock%}
{% block postnavbar %}
{% endblock%}

Hectione/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hectione</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {# Google font #}
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
  </head>
  <body>

    {% block prenavbar %}
    {% endblock %}
      <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light background transparent">
      <a class="navbar-brand brandstyle mr-auto" href="{% url 'blog:index' %}">Hectione</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mr-auto">
          <!-- empty -->
        </div>
        <div class="navbar-nav">
          <a class="nav-item nav-link mr-sm-2" href="{% url 'blog:about' %}">About</a>
          <a class="nav-item nav-link mr-sm-2" href="{% url 'blog:post_list' %}">Blog</a>
          <a class="nav-item nav-link " href="{% url 'blog:contact' %}">Contact</a>
        </div>
      </div>
    </nav>


    {% block navbar %}
    {% endblock %}

    <!-- conatiner -->
    {% block postnavbar %}
    {% endblock %}
  </body>
</html>

Hectione/blog/templates/blog/contact.html
{% extends "base.html" %}
{% block prenavbar %}
{% endblock%}
{% block navbar %}
<div class="home">
<div class="container">


    <h1 align="center">Contact</h1>
    <div class="formstyle">

      <!-- <form action="{url 'blog:thanks'}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" name="name" placeholder="Your Name">
        </div>
        <div class="form-group">
          <input type="text" class="form-control" name="email" placeholder="Enter Email">
        </div>
        <div class="form-group">
          <textarea rows="6" class="form-control" type="text" name="message" placeholder="Your Message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form> -->

      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>      
    </div>

</div>
</div>
{% endblock%}
{% block postnavbar %}
{% endblock%}

Hectione/blog/templates/blog/index.html
{% extends "base.html" %}
{% block prenavbar %}
{% endblock %}
{% block navbar %}
<div class="home">
<div class="container">
  <div class="box" id="shadowstyles">
    <h3>
    There is always a silver lining in our spirits...
    <br>
    Seems very distant. But it is there.
    <br>
    The silver line of hope. The silver line of surety! <br>
    No matter how HECTIC goes our lives... A HORIZON is always there!
  </h3>
  </div>
</div>
</div>
{% endblock%}
{% block postnavbar %}
{% endblock%}

Hectione/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% block prenavbar %}
{% endblock %}
{% block navbar %}
<div class="home">
<div class="container">
  <div id="blog">
    {% for post in object_list %}

      <div class="post">

          <h1 id='posttitle'><a href="#">{{ post.title }}</a></h1>
          <div class="date">
              <p>Published on: {{ post.created_on|date:"D M Y"}}</p>
          </div>
          <div class="postcontent">
              <p>{{ post.content }}</p>
          </div>
      </div>
  {% endfor %}
  </div>
</div>
</div>
{% endblock%}
{% block postnavbar %}
{% endblock%}

Hectione/blog/templates/blog/thanks.html
{% extends "base.html" %}
{% block prenavbar %}
{% endblock%}
{% block navbar %}
<div class="home">
<div class="container">
<div class="box">
  <h1>Thank you for the message !<br>
  Please expect response in 2 days</h1>
</div>
</div>
</div>
{% endblock%}
{% block postnavbar %}
{% endblock%}